{
  "url": "https://api.github.com/repos/DataDog/dd-trace-py/releases/243576595",
  "assets_url": "https://api.github.com/repos/DataDog/dd-trace-py/releases/243576595/assets",
  "upload_url": "https://uploads.github.com/repos/DataDog/dd-trace-py/releases/243576595/assets{?name,label}",
  "html_url": "https://github.com/DataDog/dd-trace-py/releases/tag/v3.12.4",
  "id": 243576595,
  "author": {
    "login": "brettlangdon",
    "id": 1320353,
    "node_id": "MDQ6VXNlcjEzMjAzNTM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1320353?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/brettlangdon",
    "html_url": "https://github.com/brettlangdon",
    "followers_url": "https://api.github.com/users/brettlangdon/followers",
    "following_url": "https://api.github.com/users/brettlangdon/following{/other_user}",
    "gists_url": "https://api.github.com/users/brettlangdon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/brettlangdon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/brettlangdon/subscriptions",
    "organizations_url": "https://api.github.com/users/brettlangdon/orgs",
    "repos_url": "https://api.github.com/users/brettlangdon/repos",
    "events_url": "https://api.github.com/users/brettlangdon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/brettlangdon/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "node_id": "RE_kwDOA6uE5s4OhK8T",
  "tag_name": "v3.12.4",
  "target_commitish": "3.12",
  "name": "3.12.4",
  "draft": false,
  "immutable": false,
  "prerelease": false,
  "created_at": "2025-08-29T19:18:13Z",
  "updated_at": "2025-08-29T19:30:02Z",
  "published_at": "2025-08-29T19:30:02Z",
  "assets": [

  ],
  "tarball_url": "https://api.github.com/repos/DataDog/dd-trace-py/tarball/v3.12.4",
  "zipball_url": "https://api.github.com/repos/DataDog/dd-trace-py/zipball/v3.12.4",
  "body": "### Bug Fixes\r\n\r\n- Tracing:\r\n    - asyncpg: Fix the error \"Error: expected pool connect callback to return an instance of 'asyncpg.connection.Connection', got 'ddtrace.contrib.internal.asyncpg.patch.\\_TracedConnection'\\`\" when a pool connection\" due to using the custom connect option. With this fix, postgres.connect spans will be created when this option is used."
}
