{
  "url": "https://api.github.com/repos/DataDog/dd-trace-py/releases/226217135",
  "assets_url": "https://api.github.com/repos/DataDog/dd-trace-py/releases/226217135/assets",
  "upload_url": "https://uploads.github.com/repos/DataDog/dd-trace-py/releases/226217135/assets{?name,label}",
  "html_url": "https://github.com/DataDog/dd-trace-py/releases/tag/v3.9.3",
  "id": 226217135,
  "author": {
    "login": "juanjux",
    "id": 277378,
    "node_id": "MDQ6VXNlcjI3NzM3OA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/277378?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/juanjux",
    "html_url": "https://github.com/juanjux",
    "followers_url": "https://api.github.com/users/juanjux/followers",
    "following_url": "https://api.github.com/users/juanjux/following{/other_user}",
    "gists_url": "https://api.github.com/users/juanjux/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/juanjux/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/juanjux/subscriptions",
    "organizations_url": "https://api.github.com/users/juanjux/orgs",
    "repos_url": "https://api.github.com/users/juanjux/repos",
    "events_url": "https://api.github.com/users/juanjux/events{/privacy}",
    "received_events_url": "https://api.github.com/users/juanjux/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "node_id": "RE_kwDOA6uE5s4Ne8yv",
  "tag_name": "v3.9.3",
  "target_commitish": "3.9",
  "name": "3.9.3",
  "draft": false,
  "prerelease": false,
  "created_at": "2025-06-18T15:45:30Z",
  "published_at": "2025-06-18T15:50:27Z",
  "assets": [

  ],
  "tarball_url": "https://api.github.com/repos/DataDog/dd-trace-py/tarball/v3.9.3",
  "zipball_url": "https://api.github.com/repos/DataDog/dd-trace-py/zipball/v3.9.3",
  "body": "# Release Notes\r\n\r\n### Bug Fixes\r\n\r\n  - Algoliasearch: Fix for potential dangling reference that could trhow an exception.  - \r\n  - Tracing: Resolves a bug where `os.system` or `subprocess.Popen` could return the wrong exception type.  \r\n  - AAP: This fix resolves an issue where the new ATO SDK track\\_user was reporting differently email, name, scope and role of the tracked user.\r\n\r\n"
}
